"""Render a StyleSpec into real design-token files for workspace templates.

The Designer's output stops being a JSON blob passed between prompts —
it becomes the actual tokens file the template's styles consume.
"""

from __future__ import annotations

from ..models import StyleSpec

_HEADER = (
    "/* Design tokens — generated by the AgentSite Designer.\n"
    "   This file is the single source of design truth for the project.\n"
    "   Reference ONLY these variables in styles; never hardcode colors. */\n\n"
)


def _font_stack(family: str, mono: bool = False) -> str:
    fallback = "ui-monospace, monospace" if mono else "system-ui, -apple-system, sans-serif"
    return f"'{family}', {fallback}"


def render_tokens_css(spec: StyleSpec, fmt: str) -> str:
    """Render tokens in the given format ('css-vars' or 'tailwind4')."""
    if fmt == "tailwind4":
        return _render_tailwind4(spec)
    return _render_css_vars(spec)


def _color_pairs(spec: StyleSpec) -> list[tuple[str, str]]:
    return [
        ("--color-primary", spec.primary_color),
        ("--color-secondary", spec.secondary_color),
        ("--color-accent", spec.accent_color),
        ("--color-bg", spec.background_color),
        ("--color-surface", spec.surface_color),
        ("--color-text", spec.text_color),
        ("--color-text-secondary", spec.text_secondary_color),
        ("--color-border", spec.border_color),
    ]


def _render_css_vars(spec: StyleSpec) -> str:
    pairs: list[tuple[str, str]] = [
        *_color_pairs(spec),
        ("--font-heading", _font_stack(spec.font_heading)),
        ("--font-body", _font_stack(spec.font_body)),
        ("--font-mono", _font_stack(spec.font_mono, mono=True)),
        ("--font-size-base", spec.font_size_base),
        ("--font-size-sm", spec.font_size_sm),
        ("--font-size-lg", spec.font_size_lg),
        ("--font-size-xl", spec.font_size_xl),
        ("--font-size-2xl", spec.font_size_2xl),
        ("--font-size-3xl", spec.font_size_3xl),
        ("--font-size-4xl", spec.font_size_4xl),
        ("--line-height", spec.line_height),
        ("--font-weight-normal", spec.font_weight_normal),
        ("--font-weight-medium", spec.font_weight_medium),
        ("--font-weight-bold", spec.font_weight_bold),
        ("--max-width", spec.max_width),
        ("--container-padding", spec.container_padding),
        ("--section-gap", spec.section_gap),
        ("--space-xs", spec.spacing_xs),
        ("--space-sm", spec.spacing_sm),
        ("--space-md", spec.spacing_md),
        ("--space-lg", spec.spacing_lg),
        ("--space-xl", spec.spacing_xl),
        ("--space-2xl", spec.spacing_2xl),
        ("--radius-sm", spec.border_radius_sm),
        ("--radius-md", spec.border_radius),
        ("--radius-lg", spec.border_radius_lg),
        ("--radius-full", spec.border_radius_full),
        ("--border-width", spec.border_width),
        ("--shadow-sm", spec.shadow_sm),
        ("--shadow-md", spec.shadow_md),
        ("--shadow-lg", spec.shadow_lg),
        ("--transition-speed", spec.transition_speed),
    ]
    body = "\n".join(f"  {name}: {value};" for name, value in pairs)
    return f"{_HEADER}:root {{\n{body}\n}}\n"


def _render_tailwind4(spec: StyleSpec) -> str:
    pairs: list[tuple[str, str]] = [
        *_color_pairs(spec),
        ("--font-heading", _font_stack(spec.font_heading)),
        ("--font-body", _font_stack(spec.font_body)),
        ("--font-mono", _font_stack(spec.font_mono, mono=True)),
        ("--radius-sm", spec.border_radius_sm),
        ("--radius", spec.border_radius),  # Tailwind DEFAULT — `rounded` utility
        ("--radius-md", spec.border_radius),
        ("--radius-lg", spec.border_radius_lg),
    ]
    body = "\n".join(f"  {name}: {value};" for name, value in pairs)
    return f"{_HEADER}@theme {{\n{body}\n}}\n"
